version: "3.0"
services:
  blog_user:
    build: ./Blog-User
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: BlogUser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      APP_PROFILE: prod
      POSTGRES_HOST: postgres


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: BlogUser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: devbinod


  post-comments-app:
    build: ./post-comment
    restart: on-failure
    environment:
      DB_HOST: mysql
      DATABASE_NAME: post_comment
      DB_ROOT: root
      DB_PASS: devbinod
    ports:
      - "8082:8080"

  post-app:
    build: ./EA-Post
    restart: on-failure
    environment:
      DB_HOST: mysql
      DATABASE_NAME: post
      DB_ROOT: root
      DB_PASS: devbinod
    ports:
      - "8083:8080"









