version: "3.0"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: BlogUser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: devbinod

  blog_user:
    container_name: blog_user
    image: skoirala/eaproject-bloguser:${GITHUB_SHA}
    build: ./Blog-User
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: BlogUser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      APP_PROFILE: prod
      POSTGRES_HOST: postgres

  post-app:
    container_name: post-app
    image: skoirala/eaproject-post:${GITHUB_SHA}
    build: ./EA-Post
    restart: on-failure
    depends_on:
      - mysql
      - post-comments-app
    environment:
      DB_HOST: mysql
      DATABASE_NAME: post
      DB_ROOT: root
      DB_PASS: devbinod
      MINIO_URL: minio
      POST_COMMENTS_URL: http://post-comments-app:8080/api/
    ports:
      - "8082:8080"

  post-comments-app:
    container_name: post-comments-app:${GITHUB_SHA}
    image: skoirala/eaproject-post-comments
    build: ./post-comment
    restart: on-failure
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DATABASE_NAME: post_comment
      DB_ROOT: root
      DB_PASS: devbinod
    ports:
      - "8083:8080"

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: ea@group10
      MINIO_ROOT_PASSWORD: ea@group10
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3