name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Deployment
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
    - name: Build the Docker image
      run: docker-compose build
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to dockerhub
      run: docker-compose push
    - name: Setup complete
      run: echo "Congrats, images pushed to dockerhub !"


